### ISSUE TITLE
How to exclude speakers?

### ISSUE THREAD

**Issue by tmchow** [hassio-addons/addon-airsonos#17]
# Problem/Motivation

> I want to be able to exclude Sonos speakers that already support AirPlay to avoid redundant speakers in the Airplay list.

## Expected behavior

> To be able to control whether a given discovered speaker is Airsonos enabled.

## Actual behavior

> Changing the Airsonos.xml so the enabled is `0` instead of `1` does not work to disable speakers.  Previously closed Issue #7 indicated this should be possible, but I'm not sure how to control the config.

## Proposed changes

> Allow us to set the IP, Speaker ID or Mac address to disable certain speakers.

**Comment by mpsamuels** [comment]
Is your config file keeping your change of 'enabled 1' to 'enabled 0' after the addon is restarted? 

I thought I had a similar problem to what you describe but soon noticed that my config file was reverting all my 'enabled 0' speakers to 'enabled 1' with each restart of the addon. After spotting the closed issue #16 I realised that one of my device names had [ and ] characters in it (thanks [LG] !) but removing the special characters from the name in the config file stopped the file being recreated with each restart and allowed my 'enabled 0' change to persist.

With exception of the odd behaviour of the config file being rewritten if it contains special characters (which appears unnecessary, and possibly not by design, as the add on itself writes the config with the special characters included and the service does start with them in place ) the 'enabled 0' function does work as expected as far as I can tell.
